apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-immich-postgresql-15-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-immich-postgresql-15
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/databases/immich-postgresql-15"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
                - b660-i5-13600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-15-1
  namespace: immich
  annotations:
    cnpg.io/nodeSerial: "1"
    cnpg.io/pvcStatus: ready
    cnpg.io/operatorVersion: 1.28.0
  labels:
    app.kubernetes.io/name: immich
    cnpg.io/cluster: immich-postgresql-15
    cnpg.io/instanceRole: primary
    cnpg.io/pvcRole: PG_DATA
    cnpg.io/podRole: instance
    cnpg.io/instanceName: immich-postgresql-15-1
    role: primary
spec:
  storageClassName: local-immich-postgresql-15
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
