apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netboot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: network
  sources:
    - repoURL: 'https://github.com/sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
      path: "k8s/k3s-home/argocd/network/netboot/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: app-template
      repoURL: 'https://bjw-s-labs.github.io/helm-charts'
      targetRevision: 4.5.0
      helm:
        releaseName: "netboot"
        valueFiles:
          - $values/k8s/k3s-home/argocd/network/netboot/values.yaml
