apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-valheim-pv
  namespace: games
  labels:
    app.kubernetes.io/name: valheim
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-valheim
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/valheim"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
                - b660-i5-13600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-valheim-pvc
  namespace: games
  labels:
    app.kubernetes.io/name: valheim
spec:
  storageClassName: local-valheim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
