---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
    gateway: false
    ingress: true
    traefik: false

  services.yaml: |
    - System:
        - Unifi:
            href: https://unifi
            icon: sh-ubiquiti-unifi.svg

  settings.yaml: |
    title: Homelab
    favicon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home Automation:
        style: column
        icon: home-assistant
      LLM/Ai:
        style: column
        icon: open-webui
      Apps:
        style: column
        icon: immich
      Security:
        style: column
        icon: pocket-id
      Social:
        style: column
        icon: mastodon
      Media:
        style: column
        icon: jellyfin
      Downloads:
        style: column
        icon: sonarr
      System:
        style: column
        icon: kubernetes

  widgets.yaml: |
    - search:
        provider: google
        focus: false
        showSearchSuggestions: true
        target: _blank
    - resources:
        cpu: true
        memory: true
        disk:
          - /
          - /storage
        cputemp: true
        tempmin: 0 # optional, minimum cpu temp
        tempmax: 100 # optional, maximum cpu temp
        uptime: true
        units: metric
        refresh: 3000 # optional, in ms
        diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
        network: true # optional, uses 'default' if true or specify a network interface name

  bookmarks.yaml: |
    - Tech:
        - Github:
            - abbr: GH
              href: https://github.com/sebastiaankok/home-ops
        - Kubernetes docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
        - NixOS packages:
            - abbr: Nix
              href: https://search.nixos.org/packages
    - Monitoring:
        - Grafana:
            - abbr: GF
              href: https://grafana.com/
        - Prometheus:
            - abbr: PM
              href: https://prometheus.io/docs/
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
