---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
    gateway: false
    ingress: true
    traefik: false

  settings.yaml: |
    title: Homelab
    favicon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home Automation:
        style: column
        icon: home-assistant
      LLM/Ai:
        style: column
        icon: open-webui
      Apps:
        style: column
        icon: immich
      Security:
        style: column
        icon: pocket-id
      Social:
        style: column
        icon: mastodon
      Media:
        style: column
        icon: jellyfin
      Downloads:
        style: column
        icon: sonarr
      Kubernetes:
        style: column
        icon: kubernetes

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
    - search:
        provider: duckduckgo
        focus: false
        target: _blank

  bookmarks.yaml: ""

  services.yaml: ""
