---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
    gateway: false
    ingress: true
    traefik: false

  services.yaml: |
    - System:
        - ArgoCD:
            href: https://argocd.otohgunga.nl
            icon: sh-argo-cd.svg
        - Unifi:
            href: https://unifi
            icon: sh-ubiquiti-unifi.svg

  settings.yaml: |
    title: Homelab
    favicon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home Automation:
        style: column
        icon: home-assistant
      LLM/Ai:
        style: column
        icon: open-webui
      Apps:
        style: column
        icon: immich
      Security:
        style: column
        icon: pocket-id
      Social:
        style: column
        icon: mastodon
      Media:
        style: column
        icon: jellyfin
      Downloads:
        style: column
        icon: sonarr
      System:
        style: column
        icon: kubernetes

  widgets.yaml: |
    - search:
        provider: google
        focus: false
        showSearchSuggestions: true
        target: _blank

  bookmarks.yaml: |
    - Git:
        - Kubesearch:
            - icon: kubernetes-dashboard.png
              description: Helm Chart Search
              href: https://kubesearch.dev/
        - home-ops:
            - icon: github.png
              description: Home-ops repo
              href: https://github.com/sebastiaankok/home-ops
